### ISSUE TITLE
Pirate game conceptual UI/layout designs

### ISSUE THREAD

**Issue by SharktasticA** [JakeP121/BrainsEden2018#2]
Conceptualizing the UI and other visual aspects of the game on paper so we can get a feel for how the game will look and allow us to discuss what we can do to improve it.

**Comment by JackSmerdon-zz** [comment]
![image](https://user-images.githubusercontent.com/22683156/42706461-bfe6cd88-86ce-11e8-8fba-f349d12a3cee.png)
Here is my drawn design of the interface that would be seen by players that aren't playing as the captain - drawn with a space theme but could be changed to a boat with a similar design. Fixed camera 3D, 'Captain's Orders' at the top, captain character sits at the right or back of the ship with the crew scrambling across the floor to complete their orders.

**Comment by SharktasticA** [comment]
Game idea abandoned
